Merge hw1
Nikolaenko94/Auto-JS-2021 pull request #1
Opened 2021-03-19 20:43 UTC by Nikolaenko94

@vitalics ,  homework 1 - done;

2021-03-19 20:58 UTC, vitalics requested changes

2021-03-19 20:58 UTC, vitalics commented on hw1/farm.js
> +        totalRabbitsNumber = Math.round(totalRabbitsNumber);
round - округляет по математическим правилам. т.е если у нас 1.7 кроликов то будет в итоге 2?

2021-03-19 21:03 UTC, Nikolaenko94 commented on hw1/farm.js
> +        totalRabbitsNumber = Math.round(totalRabbitsNumber);
упс, действительно, что то я не подумал, что с кроликами так не должно работать.
Необходимо использовать floor

2021-03-20 13:16 UTC, Nikolaenko94 commented on hw1/farm.js
> +        totalRabbitsNumber = Math.round(totalRabbitsNumber);
> round - округляет по математическим правилам. т.е если у нас 1.7 кроликов то будет в итоге 2?

  **Исправлено**

2021-03-20 17:49 UTC, vitalics approved these changes

2021-03-20 18:16 UTC, merged