Homework6 - done
Nikolaenko94/Auto-JS-2021 pull request #6
Opened 2021-04-07 22:36 UTC by Nikolaenko94

@vitalics  homework6 -done

2021-04-08 17:44 UTC, vitalics commented on hw5/task1/calculator.js
> +            result.result.emit('result', emitter.emit('plus', arr[0],arr[1]));
too many result.result strings

2021-04-08 18:10 UTC, vitalics requested changes

2021-04-08 18:10 UTC, vitalics commented on hw6/task2/loading.js
> +            setTimeout(() => {
too many nested `setTimeout`. Try to optimize it.
P.S. recursive call may helps you
P.P.S Thing about the long operations. You must see many repeatable loader states.

2021-04-08 18:10 UTC, vitalics commented on hw6/task1/library.js
> +    search(value){
search should work in entities that already has in Library class. that means - you can iterate evety of your arrays([see declaration line](https://github.com/Nikolaenko94/Auto-JS-2021/pull/6/files#diff-0ed900fd14b64e674fdf8e7dc523034d9c63dcebe14c33dd2981aeca1c5f266eR4)). and create a new array for finded entities. [Array.prototype.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) method can helps you

2021-04-08 22:23 UTC, Nikolaenko94 commented on hw6/task2/loading.js
> +            setTimeout(() => {
Fixed.

`let i =0 ;` 
`const asyncFn = function(){    `
            `setTimeout(function() {`
           ` let symbols = ["|","/","-","\\"];`   
           ` console.clear();`
           ` console.log(symbols[i]);`
           ` i++;`
            `if(i === symbols.length){return}`
            `asyncFn();   `
`}, 500);`
`};`

2021-04-15 07:53 UTC, vitalics requested changes

2021-04-15 07:53 UTC, vitalics commented on hw6/task1/library.js
> +        myArguments.push(...args);
`args` is already an array since you're using spread operator

2021-04-15 07:53 UTC, vitalics commented on hw6/task1/library.js
> +            if(myArguments[0].constructor.name === "Track"){
why not use `instanceof` operator?

2021-04-15 07:53 UTC, vitalics commented on hw6/task1/library.js
> +        const EventEmitter = require('events');
all imports should be declared at the start of file, no matter where we use this variable

2021-04-15 07:53 UTC, vitalics commented on hw6/task2/loading.js
> +    (resolve) => setTimeout(() => {
resolve is never used. Promise will never get the result

2021-04-15 07:53 UTC, vitalics commented on hw6/task2/loading.js
> +module.exports = {
only 1 function should be exportable. I just want to use api such as:
``` js
loading().then(() => console.log('all done'))
```

2021-04-15 19:22 UTC, merged